### ISSUE TITLE
exit code: 0xc0000096, STATUS_PRIVILEGED_INSTRUCTION

### ISSUE THREAD

**Issue by J-F-Liu** [deadblackclover/pc-beeper#2]
Got this error on Windows 11. So in what enviroment can this crate be used?

**Comment by deadblackclover** [comment]
@J-F-Liu This crate is `no_std`. It can be used when developing operating systems.

I developed crate on Ubuntu 20.04. There is a `testing` folder in the repository that has a minimal set to test crate.
